name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Dioxus CLI
        run: curl -sSL https://dioxus.dev/install.sh | bash

      - name: Build
        run: dx build --release

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/dx/serde-json-live/release/web/public
          branch: gh-pages
